### ISSUE TITLE
Running ExampleScene Error

### ISSUE THREAD

**Issue by sunbrando** [yoshidan/UniBT#1]
#
![20210207161943](https://user-images.githubusercontent.com/9989440/107140930-7a072e80-6960-11eb-90a5-f38aed9e56ae.png)
Unity 2019.4.0f1

**Comment by yoshidan** [comment]
Thank you. Now I fixed the problem. 
https://github.com/yoshidan/UniBT/releases/tag/v0.0.2

<img width="648" alt="スクリーンショット 2021-02-07 19 33 32" src="https://user-images.githubusercontent.com/958174/107144073-007d3980-697c-11eb-8f60-0f50837fdebc.png">

**Comment by sunbrando** [comment]
Thanks for Sharing
